INSERT INTO JHI_USER (ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, ACTIVATED, ACTIVATION_KEY, EMAIL, FIRST_NAME, IMAGE_URL, LANG_KEY, LAST_NAME, LOGIN, PASSWORD_HASH, RESET_DATE, RESET_KEY) VALUES (1, 'admin', null, 'admin', null, true, null, 'admin@admin.pl', 'admin',null,'pl','admin', 'admin', '$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC', null, null);

INSERT INTO JHI_AUTHORITY (name) VALUES ('ROLE_ADMIN');
INSERT INTO JHI_AUTHORITY (name) VALUES ('ROLE_USER');

INSERT INTO JHI_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO JHI_USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');
